---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s-r8
  region: us-east-1
vpc:
  id: "vpc-d9946ba0"  # (optional, must match VPC ID used for each subnet below)
  cidr: "10.0.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      us-east-1e:
        id: "subnet-0942a093fa78532a6"
        cidr: "10.0.30.0/24" # (optional, must match CIDR used by the given subnet)
      us-east-1c:
        id: "subnet-a8804f84"
        cidr: "10.0.20.0/24"  # (optional, must match CIDR used by the given subnet)
      us-east-1b:
        id: "subnet-ac1722c9"
        cidr: "10.0.10.0/24"   # (optional, must match CIDR used by the given subnet)
    private:
      us-east-1a:
        id: "subnet-052f85267095fc50b"
        cidr: "10.0.31.0/24"
      us-east-1b:
        id: "subnet-0268d87238bec52e2"
        cidr: "10.0.32.0/24"
      us-east-1c:
        id: "subnet-0ea8af06c7678feb8"
        cidr: "10.0.33.0/24"
nodeGroups:
  - name: dtk-node-group-1.16
    instanceType: t3.medium
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        albIngress: true
    ssh:
      allow: true
